<a href="https://colab.research.google.com/github/AishlyManglani/Deep-Learning_-CMPE258/blob/main/tensor%20operation/tensor_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [5]:
# Tensor Creation
scalar = torch.tensor(100)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2], [3, 4]])
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:", matrix)
print("3D Tensor:", tensor_3d)

Scalar: tensor(100)
Vector: tensor([1, 2, 3])
Matrix: tensor([[1, 2],
        [3, 4]])
3D Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [6]:
# Basic Tensor Operations
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

add = a + b
sub = a - b
mul = a * b
div = a / b

einsum_example = torch.einsum('ij, jk -> ik', [a, b.T])  # Einstein Summation

print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", mul)
print("Division:\n", div)
print("Einsum Example (Matrix Multiplication):\n", einsum_example)

Addition:
 tensor([[ 6,  8],
        [10, 12]])
Subtraction:
 tensor([[-4, -4],
        [-4, -4]])
Multiplication:
 tensor([[ 5, 12],
        [21, 32]])
Division:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
Einsum Example (Matrix Multiplication):
 tensor([[17, 23],
        [39, 53]])


In [7]:
# Reshaping and Transposing
reshaped = a.view(1, 4)
transposed = a.T
print("Reshaped Tensor:\n", reshaped)
print("Transposed Tensor:\n", transposed)

Reshaped Tensor:
 tensor([[1, 2, 3, 4]])
Transposed Tensor:
 tensor([[1, 3],
        [2, 4]])


In [8]:
# Broadcasting Example
x = torch.tensor([[1], [2], [3]])
y = torch.tensor([4, 5, 6])
broadcasted_add = x + y
print("Broadcasted Addition:\n", broadcasted_add)

Broadcasted Addition:
 tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])


In [9]:
# Advanced Tensor Operations
softmax = torch.nn.functional.softmax(a.float(), dim=1)
exp = torch.exp(a.float())
log = torch.log(a.float())
sqrt = torch.sqrt(a.float())

print("Softmax:\n", softmax)
print("Exponential:\n", exp)
print("Logarithm:\n", log)
print("Square Root:\n", sqrt)

Softmax:
 tensor([[0.2689, 0.7311],
        [0.2689, 0.7311]])
Exponential:
 tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
Logarithm:
 tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])
Square Root:
 tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


In [11]:
# Additional Tensor Operations
inverse = torch.linalg.inv(a.float()) if a.shape[0] == a.shape[1] else "Not Square"
outer_product = torch.ger(vector, vector)
cumsum = torch.cumsum(a, dim=0)
cumprod = torch.cumprod(a, dim=0)
flip = torch.flip(a, dims=[0])

def custom_function(x):
    return x**3 + 2*x + 1

custom_applied = custom_function(a.float())

print("Inverse:\n", inverse)
print("Outer Product:\n", outer_product)
print("Cumulative Sum:\n", cumsum)
print("Cumulative Product:\n", cumprod)
print("Flipped Tensor:\n", flip)
print("Custom Function Applied:\n", custom_applied)

Inverse:
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])
Outer Product:
 tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])
Cumulative Sum:
 tensor([[1, 2],
        [4, 6]])
Cumulative Product:
 tensor([[1, 2],
        [3, 8]])
Flipped Tensor:
 tensor([[3, 4],
        [1, 2]])
Custom Function Applied:
 tensor([[ 4., 13.],
        [34., 73.]])
