<a href="https://colab.research.google.com/github/AishlyManglani/Deep-Learning_-CMPE258/blob/main/tensor%20operation/tensor_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np



In [10]:
# Tensor Creation
scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"Scalar:, {scalar}")
print(f"Vector:, {vector}")
print(f"Matrix:, {matrix}")
print(f"3D Tensor:, {tensor_3d}")

Scalar:, 5
Vector:, [1 2 3]
Matrix:, [[1 2]
 [3 4]]
3D Tensor:, [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Basic Tensor Operations
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

einsum_example = tf.einsum('ij, jk -> ik', a, tf.transpose(b))  # Einstein Summation

print("Addition:\n", add.numpy())
print("Subtraction:\n", sub.numpy())
print("Multiplication:\n", mul.numpy())
print("Division:\n", div.numpy())
print("Einsum Example (Matrix Multiplication):\n", einsum_example.numpy())

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Einsum Example (Matrix Multiplication):
 [[17 23]
 [39 53]]


In [11]:
# Dot product of vectors
v1 = tf.constant([1., 2., 3.])
v2 = tf.constant([4., 5., 6.])
print("\nDot product using einsum:")
print(tf.einsum('i,i->', v1, v2))

# Outer product
print("\nOuter product using einsum:")
print(tf.einsum('i,j->ij', v1, v2))

# Batch matrix multiplication
batch1 = tf.constant([[[1,2],[3,4]], [[5,6],[7,8]]])
batch2 = tf.constant([[[9,10],[11,12]], [[13,14],[15,16]]])
print("\nBatch matrix multiplication using einsum:")
print(tf.einsum('bij,bjk->bik', batch1, batch2))


Dot product using einsum:
tf.Tensor(32.0, shape=(), dtype=float32)

Outer product using einsum:
tf.Tensor(
[[ 4.  5.  6.]
 [ 8. 10. 12.]
 [12. 15. 18.]], shape=(3, 3), dtype=float32)

Batch matrix multiplication using einsum:
tf.Tensor(
[[[ 31  34]
  [ 71  78]]

 [[155 166]
  [211 226]]], shape=(2, 2, 2), dtype=int32)


In [4]:
# Reshaping and Transposing
reshaped = tf.reshape(a, (1, 4))
transposed = tf.transpose(a)
print("Reshaped Tensor:\n", reshaped.numpy())
print("Transposed Tensor:\n", transposed.numpy())


Reshaped Tensor:
 [[1 2 3 4]]
Transposed Tensor:
 [[1 3]
 [2 4]]


In [5]:
# Broadcasting Example
x = tf.constant([[1], [2], [3]])
y = tf.constant([4, 5, 6])
broadcasted_add = x + y
print("Broadcasted Addition:\n", broadcasted_add.numpy())

Broadcasted Addition:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [7]:
# Advanced Tensor Operations
softmax = tf.nn.softmax(tf.cast(a, tf.float32), axis=1) # Cast tensor 'a' to tf.float32
exp = tf.exp(tf.cast(a, tf.float32))
log = tf.math.log(tf.cast(a, tf.float32))
sqrt = tf.math.sqrt(tf.cast(a, tf.float32))

print("Softmax:\n", softmax.numpy())
print("Exponential:\n", exp.numpy())
print("Logarithm:\n", log.numpy())
print("Square Root:\n", sqrt.numpy())


Softmax:
 [[0.26894143 0.7310586 ]
 [0.26894143 0.7310586 ]]
Exponential:
 [[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]]
Logarithm:
 [[0.        0.6931472]
 [1.0986123 1.3862944]]
Square Root:
 [[1.        1.4142135]
 [1.7320508 2.       ]]
